site_name: S-AES

nav:
  - Introducción: index.md
  - Metodología: metodology.md
  - Resultados: results.md
  - Referencias: references.md

theme:
  name: material
  locale: es

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
